name: Wake up Render bot

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to bot
        run: curl -sS -o /dev/null --max-time 120 https://telegram-chatbot-1-8ub6.onrender.com/
